apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 6
  template:
    metadata:
      labels:
        role: hello
    spec:
      containers:
        - name: hello
          image: gcr.io/google-samples/hello-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env: # Environment variables
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
          resources:
            requests: # Minimum ensured resources
              memory: "128Mi" # RAM
              cpu: "150m" # Load in mili-cpus
            limits: # Maximum allowed resources (if they are free in a node)
              memory: "512Mi"
              cpu: "300m"
