apiVersion: v1
kind: Service
metadata:
  name: hpa-lb
  namespace: testing
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: hpa
    